In [1]:
import numpy as np

In [2]:
import sys

## What is numpy?

#### Numpy is a multi dimensional array Library , 1D , 2D and 3D .

## Why is Numpy Faster?

- Faster to read less bytes of memory
- Numpy uses contigious memory location , Benefits:- Computers have <b>SIMD(Single Instrunction Multiple values) Vector Processing </b> Units, which are contigous . So this can take benifit of Processing Architecture . And Also Effect Cache Utilization .

In [4]:
a = np.array([1,2,3])

In [5]:
print(a)

[1 2 3]


In [6]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [8]:
# Get Dimensions of numpy array
print(a.ndim)

1


In [9]:
print(b.ndim)

2


In [10]:
# Get Shape
a.shape

(3,)

In [11]:
b.shape

(2, 3)

In [12]:
# Get total size
a.nbytes

12

In [13]:
b.nbytes

48

In [16]:
# Get the item size
a.itemsize #int

4

In [17]:
b.itemsize # Float

8

## Accessing / Changing specific elements , rows , columns, etc

In [19]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
# Get a specific element [r,c]
a[1,5]

13

In [21]:
a[1,-2]

13

In [22]:
# Get a specific row
a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [25]:
# [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [26]:
# Change a item in a specific location
a[1,2] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 20 11 12 13 14]]


In [27]:
a[:,2] = [1,2]
a[:,3] = 6
print(a)

[[ 1  2  1  6  5  6  7]
 [ 8  9  2  6 12 13 14]]


#### 3-D example

In [28]:
b = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [29]:
# Get a specific element
b[0,:1]

array([[1, 2]])

In [30]:
b[2:3]

array([], shape=(0, 4, 2), dtype=int32)

In [31]:
b[2:4]

array([], shape=(0, 4, 2), dtype=int32)

### Initialize different type of Arrays

In [33]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
# All 1s matrix
np.ones((4,2,2,),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [38]:
# Any other number
np.full((2, 2), 10)

array([[10, 10],
       [10, 10]])

In [39]:
# Any other number (full_time)
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [40]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [41]:
# matrix of random decimal number
np.random.rand(4,2)

array([[0.22367233, 0.65954642],
       [0.33852412, 0.10497886],
       [0.25046246, 0.04546588],
       [0.39848152, 0.47252274]])